"""Printable recording sheet + manifest template for the voice_test set (test.md §1 / §9).

  python -m ml.voice.make_sheet            # → docs/voice_script_sheet.md, data/voice_test/manifest_template.csv

Each speaker records all 20 cards once; language and noise rotate so every speaker covers every
(en | hi | hinglish) × (quiet | noisy) cell — 6 speakers → 120 clips, the test.md minimum.
"""
from __future__ import annotations

import csv
import json

from ml.common.paths import DATA, REPO

CARDS_PATH = REPO / "ml/voice/voice_cards.json"
LANGS, NOISES = ("en", "hi", "hinglish"), ("quiet", "noisy")
LANG_NAME = {"en": "English", "hi": "Hindi (Devanagari)", "hinglish": "Hinglish (Roman)"}
COLUMNS = ["clip", "speaker", "lang", "noise", "card_id", "mode", "omitted", "reference_transcript"]


def cards() -> list[dict]:
    return json.loads(CARDS_PATH.read_text())["cards"]


def schedule(n_speakers: int = 6) -> list[dict]:
    rows = []
    for s in range(n_speakers):
        for i, c in enumerate(cards()):
            lang = LANGS[(i + s) % 3]
            noise = NOISES[((i // 3) + s) % 2]
            spk = f"s{s + 1}"
            rows.append({"clip": f"{spk}_{c['id']}.wav", "speaker": spk, "lang": lang, "noise": noise, "card_id": c["id"],
                         "mode": "", "omitted": "", "reference_transcript": ""})
    return rows


def sheet(rows: list[dict]) -> str:
    cs = {c["id"]: c for c in cards()}
    out = ["# Voice test — recording sheet (generated by `ml/voice/make_sheet.py`; edit the cards, not this file)", "",
           "Goal: ≥ 120 short clips from ≥ 6 people so the app's voice intake can be measured honestly (test.md §9 V2–V6).", "",
           "## How to record", "",
           "1. Use the phone you will test on, a voice-recorder app that saves **WAV** (16 kHz mono if offered), 10–25 s per clip, phone 20–30 cm from the mouth.",
           "2. *quiet* = a closed room. *noisy* = fan on full **or** traffic/TV in the background (say which in a note).",
           "3. Read the card's **facts**, put the phone down, and say them **in your own words** in the language shown "
           "(mode = `free`). Only if you get stuck, read the example line (mode = `read`). Change ka/ki, he/she naturally.",
           "4. Name the file exactly as in the table (e.g. `s1_C01.wav`) and copy it to `data/voice_test/clips/`.",
           "5. Afterwards, someone types what was **actually said** into `reference_transcript` (Hindi in Devanagari, "
           "Hinglish in Roman letters, English in English) and lists any fact that was **not** said in `omitted` "
           "(field names separated by `;`, e.g. `age_band;itch`).",
           "6. Consent: each speaker agrees that the clip is used only to test SkinNova; no names or other personal details in the clips.", "",
           "Field names for `omitted`: body_site, duration, itch, pain, changing, bleeding_or_crusting, fever_or_unwell, "
           "others_affected, new_product_or_exposure, age_band.", "", "## Fact cards", ""]
    for c in cs.values():
        out += [f"### {c['id']} — {c['facts']}", "", f"- English: {c['en']}", f"- Hinglish: {c['hinglish']}", f"- Hindi: {c['hi']}", ""]
    out += ["## Who records what", "", "| speaker | card | language | noise | file |", "|---|---|---|---|---|"]
    out += [f"| {r['speaker']} | {r['card_id']} | {LANG_NAME[r['lang']]} | {r['noise']} | `{r['clip']}` |" for r in rows]
    out += ["", "When all clips are in place: `.venv-export/bin/python -m ml.eval.eval_voice --model <model.litertlm> --tag <name>` "
            "(or `--transcripts phone.jsonl` when the model has no audio encoder).", ""]
    return "\n".join(out)


def main():
    rows = schedule()
    (REPO / "docs/voice_script_sheet.md").write_text(sheet(rows), encoding="utf-8")
    d = DATA / "voice_test"
    (d / "clips").mkdir(parents=True, exist_ok=True)
    with open(d / "manifest_template.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS); w.writeheader(); w.writerows(rows)
    print(f"{len(rows)} clips → docs/voice_script_sheet.md, {d / 'manifest_template.csv'}")


if __name__ == "__main__":
    main()
