"""Build + push the Gemma 4 E2B LoRA Kaggle notebook and its private dataset.

  python -m ml.llm.notebooks.make_kaggle dataset            # (re)upload data/llm + validator code as harsh11067/skinnova-sft-data
  python -m ml.llm.notebooks.make_kaggle push --mode smoke  # L1 checks + L2 overfit (16 rec, 100 steps) + base sanity + timing
  python -m ml.llm.notebooks.make_kaggle push --mode full   # E1 training + E0/E1 eval + adapter/merged save

Uses the uv-tool Kaggle CLI 2.2.4 (`~/.local/bin/kaggle`, needs Python ≥ 3.11) because only it can request a T4
(`--accelerator NvidiaTeslaT4`); the default P100 (sm_60) is below Unsloth's minimum (sm_70).
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path

from ml.common.paths import LLM_DATA, REPO

OWNER = os.environ.get("KAGGLE_USERNAME", "harsh11067")
DATASET = f"{OWNER}/skinnova-sft-data"
KERNEL = f"{OWNER}/skinnova-gemma4-e2b-lora"
KAGGLE = str(Path.home() / ".local/bin/kaggle")
BUILD = REPO / "ml/llm/notebooks/build"

CELLS = []


def cell(src: str):
    CELLS.append(src.strip("\n"))


cell(r'''
# SkinNova — Gemma 4 E2B LoRA (plan §8, test.md §5 L1–L4). Generated by ml/llm/notebooks/make_kaggle.py — edit there.
MODE = "__MODE__"
import os
# Kaggle's T4 accelerator is 2×T4; Unsloth's auto device map split the model across cuda:0/cuda:1 and generate() failed
# ("Expected all tensors to be on the same device"). One T4 holds 16-bit E2B + LoRA.
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
''')
cell(r'''
%%capture
!pip install -q unsloth
!pip install -q --no-deps transformers==5.5.0 "tokenizers>=0.22.0,<=0.23.0"
!pip install -q "huggingface_hub>=1.5.0,<2.0" torchcodec
!pip install -q --no-deps --upgrade timm
''')
cell(r'''
import glob, json, os, random, sys, time, re, math
import torch
torch._dynamo.config.recompile_limit = 64
DATA = os.path.dirname(glob.glob("/kaggle/input/**/sft_train.jsonl", recursive=True)[0])
sys.path.insert(0, DATA + "/code")
from ml.llm.validate import validate, guard_text, count_sentences, load_rx_terms   # same validator as the app (OutputParser.kt)
from ml.voice.intake import validate_intake
OUT = "/kaggle/working"; os.makedirs(f"{OUT}/reports", exist_ok=True)
LABELS = json.load(open(f"{DATA}/code/labels.json")); KEYS = [c["key"] for c in LABELS["classes"]]
FLOOR = {c["key"]: c["tier_floor"] for c in LABELS["classes"]}
RX = [l.strip().lower() for l in open(f"{DATA}/code/rx_terms.txt") if l.strip() and not l.startswith("#")]
TR = {t: i for i, t in enumerate(["LOW", "MODERATE", "HIGH", "URGENT"])}
def load(n): return [json.loads(l) for l in open(f"{DATA}/{n}.jsonl")]
train, sval, lval = load("sft_train"), load("sft_val"), load("llm_val")
general = load("general_regression")
print("MODE", MODE, "| train", len(train), "sft_val", len(sval), "llm_val", len(lval), "| GPU", torch.cuda.get_device_name(0))
REPORT = {"mode": MODE, "gpu": torch.cuda.get_device_name(0), "dataset_meta": json.load(open(f"{DATA}/sft_data.json"))}
def save_report():
    json.dump(REPORT, open(f"{OUT}/reports/{MODE}.json", "w"), indent=1, default=str)
# Host-RAM watch: full run v6 was killed after ~28 min with no log and no outputs (container hard-killed, most likely
# host RAM). RSS / MemAvailable every 30 s go into the report; the training guard below stops cleanly if RAM runs low.
import psutil, threading
MEMLOG = []
def _mem_watch():
    proc = psutil.Process()
    while True:
        MEMLOG.append((round(time.time()), round(proc.memory_info().rss / 2**30, 2), round(psutil.virtual_memory().available / 2**30, 2),
                       round(torch.cuda.memory_reserved() / 2**30, 2) if torch.cuda.is_available() else None))
        REPORT["mem_rss_avail_gpu_gb"] = MEMLOG[-240:]
        time.sleep(30)
threading.Thread(target=_mem_watch, daemon=True).start()
''')
cell(r'''
from PIL import Image
def to_conv(r, with_answer=True, image_override=None):
    msgs = []; images = []
    for m in r["messages"]:
        if m["role"] == "system":
            # one-part list, exactly as the app sends it (LiteRT-LM Kotlin: systemInstruction = Contents.of(text) → JSON list);
            # the LiteRT template renders a list and a string identically. (A plain string was turned into a list by
            # UnslothVisionDataCollator anyway, and Unsloth's own gemma-4 template then printed the Python repr of that list.)
            msgs.append({"role": "system", "content": [{"type": "text", "text": m["content"]}]}); continue
        if m["role"] == "assistant" and not with_answer:
            continue
        content = []
        for c in m["content"]:
            if c["type"] == "image":
                images.append(image_override if image_override is not None else Image.open(f'{DATA}/{r["image"]}').convert("RGB"))
                content.append({"type": "image"})   # placeholder; the pixels go in "images"
            else:
                content.append({"type": "text", "text": c["text"]})
        msgs.append({"role": m["role"], "content": content})
    # Images travel in a separate "images" field: UnslothVisionDataCollator uses those unresized, whereas images inside
    # the messages go through process_vision_info(size_factor=32), which snaps their size (full run v7: 1,306 vs 1,320
    # tokens for the same record). Unresized = what Gemma's own processor and the phone's LiteRT-LM see.
    out = {"messages": msgs}
    if images:
        out["images"] = images
    return out
def target(r): return r["messages"][-1]["content"][0]["text"]
''')
cell(r'''
from unsloth import FastVisionModel
t0 = time.time()
try:
    model, processor = FastVisionModel.from_pretrained("unsloth/gemma-4-E2B-it", load_in_4bit=False, use_gradient_checkpointing="unsloth")
    REPORT["load_in_4bit"] = False
except torch.cuda.OutOfMemoryError:
    torch.cuda.empty_cache()
    model, processor = FastVisionModel.from_pretrained("unsloth/gemma-4-E2B-it", load_in_4bit=True, use_gradient_checkpointing="unsloth")
    REPORT["load_in_4bit"] = True
# Chat template = the one inside Google's official gemma-4-E2B-it.litertlm (ml/llm/chat_template_litertlm.jinja). The
# phone runs that template (LiteRT-LM's own Jinja engine), and the export bundles it (--jinja_chat_template_override),
# so training renders prompts exactly like the device. History: Unsloth's get_chat_template("gemma-4") printed a list
# system turn as a Python repr (smoke v4); the HF repo template uses methods LiteRT-LM's engine rejects (export v9:
# "Failed to apply template: unknown method").
LITERT_TEMPLATE = open(f"{DATA}/code/chat_template_litertlm.jinja", encoding="utf-8").read()
processor.chat_template = LITERT_TEMPLATE; processor.tokenizer.chat_template = LITERT_TEMPLATE
model = FastVisionModel.get_peft_model(model, finetune_vision_layers=False, finetune_language_layers=True,
    finetune_attention_modules=True, finetune_mlp_modules=True, r=16, lora_alpha=16, lora_dropout=0, bias="none",
    random_state=3407, use_rslora=False, loftq_config=None, target_modules="all-linear")
REPORT["load_s"] = round(time.time() - t0, 1)
REPORT["trainable_params"] = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(REPORT)
''')
cell(r'''
# ---- L1 pre-training checks (must print PASS) ----
from unsloth.trainer import UnslothVisionDataCollator
# resize="max": never resize — smoke v5 showed 5/12 image records with 13–18 more/fewer image tokens in the training path
# than in the inference path; the phone hands the photo to LiteRT-LM unchanged (Gemma 4 fits it to ≤ 2,520 patches).
collator = UnslothVisionDataCollator(model, processor, train_on_responses_only=True, resize="max",
                                     instruction_part="<|turn>user\n", response_part="<|turn>model\n", max_seq_length=2048)
s = to_conv(next(r for r in train if r["task"] == "T1"))
txt = processor.apply_chat_template(s["messages"], tokenize=False, add_generation_prompt=False)
assert txt.count("<bos>") <= 1 and "<|turn>model" in txt and "<|turn>system" in txt, txt[:400]
assert txt.index("<|image|>") < txt.index("IMAGE_MODEL_TOP3"), "image must come before text"
# template parity: training text == generation prompt + answer + end-of-turn, system turn verbatim (app form), no repr
def _tmpl(conv):
    return [{"role": m["role"], "content": [{"type": "image"} if c["type"] == "image" else {"type": "text", "text": c["text"]} for c in m["content"]]}
            for m in conv]
n_par = 0
for r in random.Random(1).sample(train, 60):
    full = processor.apply_chat_template(_tmpl(to_conv(r)["messages"]), tokenize=False, add_generation_prompt=False)
    prompt = processor.apply_chat_template(_tmpl(to_conv(r, with_answer=False)["messages"]), tokenize=False, add_generation_prompt=True)
    assert full == prompt + target(r) + "<turn|>\n", (r["id"], full[len(prompt) - 40: len(prompt) + 80])
    assert "<|turn>system\n" + r["messages"][0]["content"].strip() + "<turn|>\n" in full and "[{'" not in full, r["id"]
    n_par += 1
n_img = 0
for r in [x for x in random.Random(2).sample(train, 80) if x.get("image")][:12]:
    cb = collator([to_conv(r)])["input_ids"].shape[1]
    cv_ = to_conv(r); conv = cv_["messages"]; img = cv_["images"][0]
    ib = processor(img, processor.apply_chat_template(_tmpl(conv), tokenize=False, add_generation_prompt=False),
                   add_special_tokens=False, return_tensors="pt")["input_ids"].shape[1]
    assert cb == ib, (r["id"], cb, ib, "training and inference paths tokenise the image differently")
    n_img += 1
batch = collator([s]); lab = batch["labels"][0]; ids = batch["input_ids"][0]
seen = processor.tokenizer.decode(ids)
assert s["messages"][0]["content"][0]["text"].strip() in seen and "[{'" not in seen, "collator changed the system turn"
visible = processor.tokenizer.decode(ids[lab != -100])
assert visible.strip().startswith("{") and "IMAGE_MODEL_TOP3" not in visible, visible[:300]
lens = []
for r in random.Random(0).sample(train, 200):
    b = collator([to_conv(r)]); lens.append(int(b["input_ids"].shape[1]))
lens.sort(); p99 = lens[int(.99 * len(lens)) - 1]
REPORT["L1"] = {"template_ok": True, "template_parity_checked": n_par, "image_token_parity_checked": n_img, "masking_ok": True, "visible_head": visible[:120], "tokens_p50": lens[100], "tokens_p99": p99, "tokens_max": lens[-1]}
assert p99 <= 2048, p99
print("L1 PASS", REPORT["L1"]); save_report()
''')
cell(r'''
# ---- inference helpers ----
def gen(r, max_new_tokens=700, image_override=None, adapter=True):
    cv_ = to_conv(r, with_answer=False, image_override=image_override); conv = cv_["messages"]; imgs = cv_.get("images", [])
    tmpl = [{"role": m["role"], "content": m["content"] if isinstance(m["content"], str) else
             [{"type": "image"} if c["type"] == "image" else {"type": "text", "text": c["text"]} for c in m["content"]]} for m in conv]
    text = processor.apply_chat_template(tmpl, add_generation_prompt=True)
    inputs = (processor(imgs[0], text, add_special_tokens=False, return_tensors="pt") if imgs else
              processor(text=text, add_special_tokens=False, return_tensors="pt")).to("cuda")
    def _g():
        return model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False, use_cache=True)
    if adapter:
        out = _g()
    else:
        with model.disable_adapter():
            out = _g()
    return processor.tokenizer.decode(out[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)

def gen_many(recs, max_new_tokens=700, image_override=None, adapter=True, bs=8):
    """Batched greedy generation (left padding); falls back to one-by-one if the processor rejects a batch."""
    outs = []
    tok = processor.tokenizer; tok.padding_side = "left"
    for s0 in range(0, len(recs), bs):
        chunk = recs[s0:s0 + bs]
        cvs_ = [to_conv(r, with_answer=False, image_override=image_override) for r in chunk]
        convs = [c["messages"] for c in cvs_]; imgs = [c.get("images", []) for c in cvs_]
        texts = [processor.apply_chat_template([{"role": m["role"], "content": m["content"] if isinstance(m["content"], str) else
                  [{"type": "image"} if c["type"] == "image" else {"type": "text", "text": c["text"]} for c in m["content"]]} for m in cv],
                  add_generation_prompt=True) for cv in convs]
        try:
            if all(imgs) and len(set(len(i) for i in imgs)) == 1:
                inputs = processor(images=imgs, text=texts, add_special_tokens=False, padding=True, return_tensors="pt").to("cuda")
            elif not any(imgs):
                inputs = processor(text=texts, add_special_tokens=False, padding=True, return_tensors="pt").to("cuda")
            else:
                raise ValueError("mixed image/text batch")
            def _g():
                return model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False, use_cache=True)
            if adapter:
                out = _g()
            else:
                with model.disable_adapter():
                    out = _g()
            n = inputs["input_ids"].shape[1]
            outs += [tok.decode(o[n:], skip_special_tokens=True) for o in out]
        except Exception as e:
            print("batch fallback:", type(e).__name__, str(e)[:120])
            outs += [gen(r, max_new_tokens, image_override, adapter) for r in chunk]
    return outs

from ml.eval.llm_metrics import score_analysis as _sa, score_extract as _se, summarize, summarize_extract, ANALYSIS_KEYS
def score_analysis(r, text): return _sa(r["meta"], text)
def score_extract(r, text): return _se(r["meta"], text)

''')
cell(r'''
# ---- base-model sanity (E0) on a few llm_val cases: proves the eval path works before any training ----
FastVisionModel.for_inference(model)
t0 = time.time(); cases = [x for x in lval if x["task"] == "T1"][:4]
outs = gen_many(cases, 700, adapter=False, bs=4)
base = [{"id": r["id"], "out": o[:1500], **score_analysis(r, o)} for r, o in zip(cases, outs)]
REPORT["E0_sanity"] = {"cases": base, "s_per_case_batched": round((time.time() - t0) / len(cases), 1)}
print(json.dumps(REPORT["E0_sanity"], indent=1)[:3000]); save_report()
''')
cell(r'''
from trl import SFTTrainer, SFTConfig
def sft_args(**kw):
    base = dict(per_device_train_batch_size=1, gradient_accumulation_steps=8, max_grad_norm=0.3, warmup_ratio=0.03,
                learning_rate=2e-4, logging_steps=5, optim="adamw_8bit", weight_decay=0.001, lr_scheduler_type="cosine",
                seed=3407, output_dir=f"{OUT}/out", report_to="none", remove_unused_columns=False, dataset_text_field="",
                dataset_kwargs={"skip_prepare_dataset": True}, max_length=2048, save_strategy="no")
    base.update(kw); return SFTConfig(**base)

if MODE == "smoke":
    # ---- L2 overfit test: 16 records, 100 steps → loss < 0.3 and ≥ 14/16 exact greedy reproductions ----
    # v4: smoke v3 reached loss 0.021 but only 3/16 exact; every divergence sat on a phrase the generator picks at random.
    # So: (a) teacher-forced token check through BOTH the training (collator) path and the inference path — a template or
    # image-token mismatch shows up as a much higher inference-path NLL; (b) batched vs one-by-one generation must agree;
    # (c) keep training in rounds of 100 steps and re-measure, to see whether exact reproduction is a capacity/steps issue.
    os.environ["UNSLOTH_RETURN_LOGITS"] = "1"
    small = [r for r in train if r["task"] in {"T1", "T2", "T3", "T4", "T9"}][:12] + [r for r in train if r["task"] in {"T6", "T7", "T8"}][:4]
    RESP_IDS = processor.tokenizer.encode("<|turn>model\n", add_special_tokens=False)
    def _prompt_inputs(r, suffix=""):
        cv_ = to_conv(r, with_answer=False); conv = cv_["messages"]; imgs = cv_.get("images", [])
        tmpl = [{"role": m["role"], "content": m["content"] if isinstance(m["content"], str) else
                 [{"type": "image"} if c["type"] == "image" else {"type": "text", "text": c["text"]} for c in m["content"]]} for m in conv]
        text = processor.apply_chat_template(tmpl, add_generation_prompt=True) + suffix
        return (processor(imgs[0], text, add_special_tokens=False, return_tensors="pt") if imgs else
                processor(text=text, add_special_tokens=False, return_tensors="pt")).to("cuda")
    @torch.no_grad()
    def teacher_forced(r, path):
        if path == "collator":
            b = {k: (v.to("cuda") if hasattr(v, "to") else v) for k, v in collator([to_conv(r)]).items()}
            lab = b.pop("labels")[0]; ids = b["input_ids"][0]; pos = (lab != -100).nonzero().flatten()
        else:
            b = _prompt_inputs(r, target(r) + "<turn|>\n"); ids = b["input_ids"][0]; L = ids.tolist(); n = len(RESP_IDS)
            st = max(i for i in range(len(L) - n + 1) if L[i:i + n] == RESP_IDS) + n
            pos = torch.arange(st, len(L), device=ids.device)
        logits = model(**b).logits[0]
        lp = torch.log_softmax(logits[pos - 1].float(), -1); tgt = ids[pos]
        pt = lp.gather(1, tgt[:, None]).squeeze(1); am = lp.argmax(-1)
        mism = (am != tgt).nonzero().flatten().tolist(); dec = processor.tokenizer.decode
        return {"n_input_tokens": int(ids.shape[0]), "pixel_values": list(b["pixel_values"].shape) if "pixel_values" in b else None,
                "n_target": int(tgt.shape[0]), "nll_mean": round(float(-pt.mean()), 4), "nll_sum": round(float(-pt.sum()), 2),
                "argmax_mismatches": len(mism),
                "first_mismatches": [{"context": dec(tgt[max(0, i - 10):i]), "target": dec(tgt[i:i + 1]), "argmax": dec(am[i:i + 1]),
                                      "p_target": round(float(pt[i].exp()), 3)} for i in mism[:5]]}
    def decisions(o, task):
        if task == "T7":
            return o.strip()            # narration: plain text
        try:
            j = json.loads(o)
        except Exception:
            return None
        if isinstance(j, dict) and "possible_categories" in j:
            try:
                return ([(c["key"], c["likelihood"]) for c in j["possible_categories"]], j["uncertainty"]["level"],
                        j["triage"]["tier"], j.get("disagreement_with_image_model"))
            except Exception:
                return None
        return j                         # extraction / translation: the whole object
    def evaluate_small(tag):
        FastVisionModel.for_inference(model)
        exact = jsoneq = deceq = 0; outs = []
        for r, o in zip(small, gen_many(small, 700, bs=4)):
            o = o.strip(); t = target(r).strip(); ok = o == t; exact += ok
            try:
                je = json.loads(o) == json.loads(t)
            except Exception:
                je = False
            jsoneq += je
            dec = decisions(o, r["task"]); dec_ok = dec is not None and dec == decisions(t, r["task"]); deceq += dec_ok
            diff = next((i for i, (a, b) in enumerate(zip(o, t)) if a != b), min(len(o), len(t)))
            outs.append({"id": r["id"], "task": r["task"], "exact": ok, "json_equal": je, "decisions_equal": dec_ok, "first_diff": diff, "len_out": len(o), "len_target": len(t),
                         "out_at_diff": o[max(0, diff - 60): diff + 60], "target_at_diff": t[max(0, diff - 60): diff + 60], "out": o})
        print(tag, "exact", exact, "json_equal", jsoneq, "decisions_equal", deceq, flush=True)
        return exact, jsoneq, deceq, outs
    rounds = []; total_steps = 0; t_train = 0.0
    for rnd in range(2):
        FastVisionModel.for_training(model)
        trainer = SFTTrainer(model=model, train_dataset=[to_conv(r) for r in small], processing_class=processor.tokenizer,
                             data_collator=collator, args=sft_args(gradient_accumulation_steps=1, max_steps=100, warmup_ratio=0.0))
        t0 = time.time(); trainer.train(); dt = time.time() - t0; t_train += dt; total_steps += 100
        losses = [h["loss"] for h in trainer.state.log_history if "loss" in h]
        exact, jsoneq, deceq, outs = evaluate_small(f"after {total_steps} steps")
        rec = {"steps": total_steps, "losses": losses, "final_loss": losses[-1], "exact": exact, "json_equal": jsoneq, "decisions_equal": deceq,
               "train_s": round(dt, 1), "outs": outs}
        if rnd == 0:
            REPORT["L2"] = {"first_loss": losses[0], "final_loss": losses[-1], "losses": losses, "exact": exact, "json_equal": jsoneq, "n": len(small),
                            "decisions_equal": deceq, "train_s": round(dt, 1), "s_per_step_bs1": round(dt / 100, 2),
                            "peak_mem_gb": round(torch.cuda.max_memory_reserved() / 2**30, 2), "outs": outs}
            steps_full = math.ceil(3040 / 8)   # full plan: ~3,040 records × 1 epoch
            REPORT["projection"] = {"full_steps": steps_full, "est_full_train_h": round(steps_full * 8 * dt / 100 / 3600, 2)}
            try:   # (a) training path vs inference path, same weights: same token count and ~same loss expected
                REPORT["L2_teacher_forced"] = [{"id": r["id"], "task": r["task"], "collator": teacher_forced(r, "collator"),
                                                "inference": teacher_forced(r, "inference")} for r in small]
                REPORT["L2_path_parity"] = sum(x["collator"]["n_input_tokens"] == x["inference"]["n_input_tokens"] for x in REPORT["L2_teacher_forced"])
            except Exception as e:
                REPORT["L2_teacher_forced"] = f"error: {type(e).__name__}: {e}"
            try:   # (b) batched (left-padded) vs one-by-one greedy outputs on the first 4 image records
                single = [gen(r, 700).strip() for r in small[:4]]
                REPORT["L2_batch_consistency"] = {"same": sum(a == o["out"] for a, o in zip(single, outs[:4])), "n": 4,
                                                  "single": [s_[:300] for s_ in single]}
            except Exception as e:
                REPORT["L2_batch_consistency"] = f"error: {type(e).__name__}: {e}"
        rounds.append(rec); REPORT["L2_rounds"] = rounds
        # test.md L2 (rev. 2026-10-06): loss < 0.3 and the record-specific decisions (categories + order, likelihoods,
        # uncertainty level, tier, disagreement; whole object for extraction/translation; text for narration) reproduce
        # for ≥ 14/16 within 200 steps. Word-for-word output is reported, not gated: the generator draws paraphrases at random.
        REPORT["L2"]["pass"] = bool(losses[-1] < 0.3 and deceq >= 14)
        REPORT["L2"]["pass_at_steps"] = REPORT["L2"].get("pass_at_steps") or (total_steps if REPORT["L2"]["pass"] else None)
        save_report()
    print("L2", "PASS" if REPORT["L2"]["pass"] else "FAIL", {k: REPORT["L2"][k] for k in ["first_loss", "final_loss", "exact", "train_s", "peak_mem_gb"]},
          REPORT["projection"], "| rounds:", [(x["steps"], round(x["final_loss"], 4), x["exact"], x["json_equal"], x["decisions_equal"]) for x in rounds],
          "| path parity", REPORT.get("L2_path_parity"))
    if isinstance(REPORT.get("L2_teacher_forced"), list):
        for x in REPORT["L2_teacher_forced"]:
            print(x["id"], "collator nll", x["collator"]["nll_mean"], "tok", x["collator"]["n_input_tokens"], "| inference nll", x["inference"]["nll_mean"],
                  "tok", x["inference"]["n_input_tokens"], "| mism", x["collator"]["argmax_mismatches"], x["inference"]["argmax_mismatches"])
    print("batch consistency", REPORT.get("L2_batch_consistency", {}).get("same") if isinstance(REPORT.get("L2_batch_consistency"), dict) else REPORT.get("L2_batch_consistency"))
    save_report()
''')
cell(r'''
if MODE == "full":
    # ---- E1: full training (plan §8.3), eval loss on sft_val ----
    FastVisionModel.for_training(model)
    # Lazy images: the datasets are lists of ids; the collator's formatting_func builds the conversation (and decodes the
    # image) only when a batch is formed — no 3,040 decoded PIL images held in RAM for the whole run.
    from transformers import TrainerCallback
    REC = {r["id"]: r for r in train + sval}
    def fmt(ex):
        return to_conv(REC[ex["id"]])
    train_collator = UnslothVisionDataCollator(model, processor, formatting_func=fmt, train_on_responses_only=True, resize="max",
                                               instruction_part="<|turn>user\n", response_part="<|turn>model\n", max_seq_length=2048)
    class Guard(TrainerCallback):
        def on_step_end(self, args, state, control, **kw):
            if psutil.virtual_memory().available < 3 * 2**30:
                REPORT["train_stopped"] = f"host RAM below 3 GB at step {state.global_step}"
                control.should_training_stop = True; control.should_save = True
            if state.global_step % 20 == 0:
                REPORT["train_progress"] = {"step": state.global_step, "max_steps": state.max_steps, "log_tail": state.log_history[-3:]}
                save_report()
    _b = train_collator([{"id": train[0]["id"]}])   # fail fast if the lazy path differs from the eager one checked in L1
    _e = collator([to_conv(train[0])])
    assert torch.equal(_b["input_ids"], _e["input_ids"]) and torch.equal(_b["labels"], _e["labels"]), "lazy collator path differs"
    trainer = SFTTrainer(model=model, train_dataset=[{"id": r["id"]} for r in train], eval_dataset=[{"id": r["id"]} for r in sval],
                         processing_class=processor.tokenizer, data_collator=train_collator, callbacks=[Guard()],
                         args=sft_args(num_train_epochs=1, eval_strategy="steps", eval_steps=100, per_device_eval_batch_size=1,
                                       save_strategy="steps", save_steps=100, save_total_limit=2, load_best_model_at_end=True,
                                       metric_for_best_model="eval_loss", greater_is_better=False))
    t0 = time.time(); trainer.train(); dt = time.time() - t0
    REPORT["train"] = {"wall_h": round(dt / 3600, 2), "log": trainer.state.log_history, "best": trainer.state.best_metric,
                       "peak_mem_gb": round(torch.cuda.max_memory_reserved() / 2**30, 2)}
    model.save_pretrained(f"{OUT}/lora"); processor.save_pretrained(f"{OUT}/lora")
    save_report()
''')
cell(r'''
if MODE == "full":
    # ---- L4: E0 (adapter off) vs E1 on llm_val; image ablation; extraction; forgetting set ----
    FastVisionModel.for_inference(model)
    an = [r for r in lval if r["task"] in {"T1", "T9"}][:40]
    ex = [r for r in lval if r["task"] == "T6"][:20]
    res = {}
    for arm, adapter in [("E1", True), ("E0", False)]:
        outs = gen_many(an, 700, adapter=adapter)
        res[arm] = [{"id": r["id"], "task": r["task"], **score_analysis(r, o), "out": o} for r, o in zip(an, outs)]
        save_report()
    REPORT["L4_analysis"] = {arm: summarize(rows, ANALYSIS_KEYS) for arm, rows in res.items()}
    REPORT["L4_analysis_rows"] = res
    gray = Image.new("RGB", (512, 512), (128, 128, 128))
    gouts = gen_many(an[:16], 700, image_override=gray)
    abl = [{"id": r["id"], "real": row["cats"], "gray": score_analysis(r, o)["cats"]} for r, o, row in zip(an[:16], gouts, res["E1"][:16])]
    for x in abl: x["changed"] = set(x["real"]) != set(x["gray"])
    REPORT["image_ablation"] = {"changed_rate": round(sum(x["changed"] for x in abl) / len(abl), 3), "rows": abl}
    # same 16 cases WITHOUT image-model scores (the T10 setting): does the photo drive the answer when CV is absent?
    import copy, re as _re
    def _nocv(r):
        r2 = copy.deepcopy(r)
        for c in r2["messages"][1]["content"]:
            if c["type"] == "text":
                c["text"] = _re.sub(r"^IMAGE_MODEL_TOP3: .*$", "IMAGE_MODEL_TOP3: []", c["text"], flags=_re.M)
        return r2
    nocv = [_nocv(r) for r in an[:16]]
    real_n, gray_n = gen_many(nocv, 700), gen_many(nocv, 700, image_override=gray)
    abl2 = [{"id": r["id"], "real": score_analysis(r, a)["cats"], "gray": score_analysis(r, b)["cats"],
             "true_in_real": r["meta"]["label"] in score_analysis(r, a)["cats"]} for r, a, b in zip(an[:16], real_n, gray_n)]
    for x in abl2: x["changed"] = set(x["real"]) != set(x["gray"])
    REPORT["image_ablation_nocv"] = {"changed_rate": round(sum(x["changed"] for x in abl2) / len(abl2), 3),
                                     "true_class_listed_rate": round(sum(x["true_in_real"] for x in abl2) / len(abl2), 3), "rows": abl2}
    xr = {}
    for arm, adapter in [("E1", True), ("E0", False)]:
        outs = gen_many(ex, 300, adapter=adapter)
        xr[arm] = [{"id": r["id"], **score_extract(r, o), "out": o} for r, o in zip(ex, outs)]
    REPORT["L4_extract"] = {arm: summarize_extract(rows) for arm, rows in xr.items()}
    gq = [{"messages": [{"role": "user", "content": [{"type": "text", "text": q["prompt"]}]}]} for q in general[:20]]
    g1, g0 = gen_many(gq, 150), gen_many(gq, 150, adapter=False)
    REPORT["general_regression"] = [{"prompt": q["prompt"], "E1": a1, "E0": a0} for q, a1, a0 in zip(general, g1, g0)]
    save_report()
    print(json.dumps({k: REPORT[k] for k in ["L4_analysis", "L4_extract"]}, indent=1), REPORT["image_ablation"]["changed_rate"])
''')
cell(r'''
if MODE == "full":
    # optional: private HF copy of the LoRA adapter (Kaggle secrets HF_TOKEN / HF_USER, d2y §7); skipped if not set
    try:
        from kaggle_secrets import UserSecretsClient
        from huggingface_hub import HfApi
        tok = UserSecretsClient().get_secret("HF_TOKEN"); user = UserSecretsClient().get_secret("HF_USER")
        api = HfApi(token=tok); repo = f"{user}/skinnova-e2b-lora-v1"
        api.create_repo(repo, private=True, exist_ok=True); api.upload_folder(folder_path=f"{OUT}/lora", repo_id=repo)
        REPORT["hf_lora_repo"] = repo
    except Exception as e:
        REPORT["hf_push"] = f"skipped: {type(e).__name__}"
    # merged 16-bit weights for the .litertlm export notebook
    model.save_pretrained_merged(f"{OUT}/merged", processor, save_method="merged_16bit")
    open(f"{OUT}/merged/chat_template_litertlm.jinja", "w", encoding="utf-8").write(LITERT_TEMPLATE)
    print(os.listdir(f"{OUT}/merged"))
    # ---- L5 merge parity (test.md §5): adapter outputs (E1, already generated) vs merged 16-bit weights, same prompts ----
    import gc
    e1 = {x["id"]: x for x in REPORT["L4_analysis_rows"]["E1"]}
    # v8 OOM: the collators kept the training model alive → release every reference before reloading the merged weights
    for _n in ["trainer", "model", "collator", "train_collator", "_b", "_e"]:
        globals().pop(_n, None)
    gc.collect(); torch.cuda.empty_cache()
    REPORT["L5_gpu_before_reload_gb"] = round(torch.cuda.memory_allocated() / 2**30, 2)
    try:
        model, processor = FastVisionModel.from_pretrained(f"{OUT}/merged", load_in_4bit=False)
        processor.chat_template = LITERT_TEMPLATE; processor.tokenizer.chat_template = LITERT_TEMPLATE
        FastVisionModel.for_inference(model)
        l5 = []
        for r, o in zip(an, gen_many(an, 700, adapter=True)):
            a = e1[r["id"]]["out"]; ta, tb = processor.tokenizer.encode(a), processor.tokenizer.encode(o)
            same_prefix = next((i for i, (x, y) in enumerate(zip(ta, tb)) if x != y), min(len(ta), len(tb)))
            l5.append({"id": r["id"], "identical": a.strip() == o.strip(), "first_diff_token": same_prefix,
                       "cats_equal": set(score_analysis(r, a)["cats"]) == set(score_analysis(r, o)["cats"])})
        n = len(l5)
        REPORT["L5_merge_parity"] = {"n": n, "identical": sum(x["identical"] for x in l5) / n,
                                     "differ_after_50_tokens": sum(x["identical"] or x["first_diff_token"] >= 50 for x in l5) / n,
                                     "category_sets_equal": sum(x["cats_equal"] for x in l5) / n, "rows": l5}
        L5 = REPORT["L5_merge_parity"]   # test.md L5: identical ≥ 95 %, the rest differ only after ≥ 50 tokens, category sets ≥ 98 %
        L5["pass"] = bool(L5["identical"] >= 0.95 and L5["differ_after_50_tokens"] == 1.0 and L5["category_sets_equal"] >= 0.98)
        print("L5", {k: v for k, v in REPORT["L5_merge_parity"].items() if k != "rows"}); save_report()
    except torch.cuda.OutOfMemoryError as e:   # merged weights are already saved; L6 (HF E1 vs .litertlm) checks the merge end-to-end
        REPORT["L5_merge_parity"] = {"skipped": f"CUDA OOM reloading merged weights ({REPORT['L5_gpu_before_reload_gb']} GB still allocated)"}
        save_report()
    save_report()
''')


def notebook(mode: str) -> dict:
    cells = []
    for src in CELLS:
        src = src.replace("__MODE__", mode)
        cells.append({"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [],
                      "source": [l + "\n" for l in src.split("\n")]})
    return {"cells": cells, "metadata": {"kernelspec": {"name": "python3", "display_name": "Python 3", "language": "python"},
                                          "language_info": {"name": "python"}}, "nbformat": 4, "nbformat_minor": 5}


def push(mode: str):
    d = BUILD / f"kernel_{mode}"
    if d.exists():
        shutil.rmtree(d)
    d.mkdir(parents=True)
    (d / "gemma4_e2b_lora.ipynb").write_text(json.dumps(notebook(mode), indent=1))
    meta = {"id": KERNEL, "title": "skinnova-gemma4-e2b-lora", "code_file": "gemma4_e2b_lora.ipynb", "language": "python",
            "kernel_type": "notebook", "is_private": True, "enable_gpu": True, "enable_tpu": False, "enable_internet": True,
            "dataset_sources": [DATASET], "competition_sources": [], "kernel_sources": [], "model_sources": [],
            "machine_shape": "NvidiaTeslaT4"}
    (d / "kernel-metadata.json").write_text(json.dumps(meta, indent=1))
    shutil.copyfile(d / "gemma4_e2b_lora.ipynb", REPO / f"ml/llm/notebooks/gemma4_e2b_lora_{mode}.ipynb")
    subprocess.run([KAGGLE, "kernels", "push", "-p", str(d), "--accelerator", "NvidiaTeslaT4"], check=True)


def dataset():
    d = BUILD / "dataset"
    if d.exists():
        shutil.rmtree(d)
    shutil.copytree(LLM_DATA, d)
    if (LLM_DATA.parent / "llm_eval").exists():   # frozen arms/safety set (ml/eval/eval_arms.py), survives SFT rebuilds
        shutil.copytree(LLM_DATA.parent / "llm_eval", d / "llm_eval")
    code = d / "code"
    for rel in ["ml/__init__.py", "ml/common/__init__.py", "ml/common/paths.py", "ml/common/schema.py", "ml/common/labels.json",
                "ml/llm/__init__.py", "ml/llm/validate.py", "ml/voice/__init__.py", "ml/voice/intake.py",
                "ml/eval/__init__.py", "ml/eval/llm_metrics.py",
                # arms / safety evaluation on Kaggle CPU (ml/eval/notebooks/make_arms.py)
                "ml/eval/eval_arms.py", "ml/eval/redflags.py", "ml/eval/bootstrap.py", "ml/llm/prompt_builder.py",
                "ml/llm/cards/condition_cards.json"] + [str(f.relative_to(REPO)) for f in sorted((REPO / "ml/llm/prompts").glob("*.txt"))]:
        (code / rel).parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(REPO / rel, code / rel)
    (code / "ml/llm/safety").mkdir(parents=True, exist_ok=True)
    shutil.copyfile(REPO / "ml/llm/safety/rx_terms.txt", code / "ml/llm/safety/rx_terms.txt")
    shutil.copyfile(REPO / "ml/llm/safety/rx_terms.txt", code / "rx_terms.txt")
    shutil.copyfile(REPO / "ml/common/labels.json", code / "labels.json")
    shutil.copyfile(REPO / "ml/llm/chat_template_litertlm.jinja", code / "chat_template_litertlm.jinja")
    shutil.copyfile(REPO / "reports/sft_data.json", d / "sft_data.json")
    (d / "dataset-metadata.json").write_text(json.dumps({"title": "skinnova-sft-data", "id": DATASET, "licenses": [{"name": "other"}]}, indent=1))
    exists = subprocess.run([KAGGLE, "datasets", "status", DATASET], capture_output=True, text=True).returncode == 0
    cmd = ([KAGGLE, "datasets", "version", "-p", str(d), "-m", "regenerated", "-r", "zip", "-d"] if exists else
           [KAGGLE, "datasets", "create", "-p", str(d), "-r", "zip"])   # private by default
    subprocess.run(cmd, check=True)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("what", choices=["dataset", "push"])
    ap.add_argument("--mode", choices=["smoke", "full"], default="smoke")
    a = ap.parse_args()
    dataset() if a.what == "dataset" else push(a.mode)
