"""Kaggle CPU notebook: HF Gemma 4 E2B → .litertlm with litert-torch export_hf, then L6-style checks with litert-lm 0.17.1.

  python -m ml.llm.notebooks.make_export --mode stock    # spike: export unmodified unsloth/gemma-4-E2B-it (vision/audio survive?)
  python -m ml.llm.notebooks.make_export --mode merged   # export our merged LoRA weights (kernel output of the training notebook)

Everything runs inside an isolated uv venv (Python 3.12) pinned to the versions verified locally in `.venv-export`
(Kaggle's preinstalled protobuf 5.x / typing_extensions broke litert-lm-builder twice). CPU session (no GPU quota); uses lightweight conversion because the default path was OOM-killed at 30 GB.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess

from ml.common.paths import REPO
from ml.llm.notebooks.make_kaggle import DATASET, KAGGLE, KERNEL, OWNER

EXPORT_KERNEL = f"{OWNER}/skinnova-gemma4-e2b-export"
LORA_DATASETS = {"lora": f"{OWNER}/skinnova-lora-v1", "lora2": f"{OWNER}/skinnova-lora-v2"}
BUILD = REPO / "ml/llm/notebooks/build"
PINS = ["litert-torch==0.9.4", "litert-lm-api==0.17.1", "litert-lm-builder==0.17.1", "ai-edge-litert==2.2.0", "ai-edge-quantizer==0.9.0",
        "litert-converter==0.4.0", "transformers==5.18.0", "tokenizers==0.23.2", "huggingface-hub==1.33.0", "protobuf==7.36.2",
        "torchao==0.18.0", "safetensors==0.8.0", "sentencepiece==0.2.2", "numpy==2.5.2", "pillow==12.3.0", "jax==0.11.2", "jaxlib==0.11.2",
        "pydantic", "python-dotenv", "soundfile", "datasets", "peft"]
RUN_PY = (REPO / "ml/llm/notebooks/export_run.py").read_text()
PATCH_PY = (REPO / "ml/llm/notebooks/export_patched.py").read_text()


def notebook(mode: str) -> dict:
    pins = " ".join(f'"{p}"' for p in PINS)
    cells = [
        f'# SkinNova — Gemma 4 E2B → .litertlm export + checks (generated by ml/llm/notebooks/make_export.py — edit there)\nMODE = "{mode}"',
        "%%capture\n!pip install -q uv\n!uv venv /tmp/ve --python 3.12\n"
        "!uv pip install --python /tmp/ve/bin/python --index-url https://download.pytorch.org/whl/cpu \"torch==2.11.0\" \"torchvision==0.26.0\"\n"
        f"!uv pip install --python /tmp/ve/bin/python {pins}",
        "open('/tmp/run.py', 'w').write(" + repr(RUN_PY) + ")\nopen('/tmp/export_patched.py', 'w').write(" + repr(PATCH_PY) + ")",
        "import subprocess, sys\n"
        "p = subprocess.Popen(['/tmp/ve/bin/python', '/tmp/run.py', MODE], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)\n"
        "for line in p.stdout:\n    print(line, end='')\n"
        "rc = p.wait(); print('exit code', rc)\nassert rc == 0, 'export suite failed — see /kaggle/working/reports'",
    ]
    return {"cells": [{"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [], "source": [l + "\n" for l in c.split("\n")]}
                      for c in cells],
            "metadata": {"kernelspec": {"name": "python3", "display_name": "Python 3", "language": "python"}}, "nbformat": 4, "nbformat_minor": 5}


def push(mode: str):
    d = BUILD / f"export_{mode}"
    shutil.rmtree(d, ignore_errors=True); d.mkdir(parents=True)
    (d / "export.ipynb").write_text(json.dumps(notebook(mode), indent=1))
    shutil.copyfile(d / "export.ipynb", REPO / f"ml/llm/notebooks/export_{mode}.ipynb")
    meta = {"id": EXPORT_KERNEL, "title": "skinnova-gemma4-e2b-export", "code_file": "export.ipynb", "language": "python",
            "kernel_type": "notebook", "is_private": True, "enable_gpu": False, "enable_tpu": False, "enable_internet": True,
            # (a "Tpu1VmV38" request was silently ignored by Kaggle — TPU quota stayed 0.00 h — so stay on the CPU machine)
            "dataset_sources": [DATASET] + ([LORA_DATASETS[mode]] if mode in LORA_DATASETS else []), "competition_sources": [],
            "kernel_sources": [KERNEL] if mode == "merged" else [], "model_sources": []}
    (d / "kernel-metadata.json").write_text(json.dumps(meta, indent=1))
    subprocess.run([KAGGLE, "kernels", "push", "-p", str(d)], check=True)


if __name__ == "__main__":
    ap = argparse.ArgumentParser(); ap.add_argument("--mode", choices=["stock", "merged", "lora", "lora2"], required=True)
    a = ap.parse_args()
    push(a.mode)
